sudo: true
service: docker
language: ruby
cache:
- bundler
before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- gem build sensu-plugins-opsgenie.gemspec
- gem install sensu-plugins-opsgenie-*.gem
- bundle exec rake quick
- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
deploy:
  provider: rubygems
  api_key:
    secure: K0vq7Ahny7bZIz1LnilosmNgHG/L4Nv6QuPaxo++/lQ7dWT9puRDLFw/pQI7+Xgb+LBLWFW2ye33q01qd1Cke8nuMKQduxnGeBzzH6fHJiXDcz5uEoKB2a8qdkwHHP3y9fisGaZgyhxlmui3fny3C0JjFizs9oNNYIt3MZcETTk=
  gem: sensu-plugins-opsgenie
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-opsgenie
